### ISSUE TITLE
Uploading large files

### ISSUE THREAD

**Issue by linus-ha** [urpylka/docker-aptly#10]
I have some .deb files larger than 100 MB. When uploading them, I get back an HTTP error of 413 - Request Entity Too Large

```
user@host  ~/> ls -la
[...]
-rw-r--r-- 1 user user 125155444 21. Mai 2020  somefile.deb

user@host ~/> curl -X POST --user xy:pass -F file=@somefile.deb https://example.com/api/files/destdir
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The limit is set in `nginx.conf` of this container (path inside container: `/etc/nginx/conf.d/default.conf`):
https://github.com/urpylka/docker-aptly/blob/0d840cdbd2f867198d4c8d34b050dbfc1774bcd1/assets/nginx.conf#L15

It would be great if that value would be configurable via an environment variable when creating the container.

**Comment by urpylka** [comment]
Hello @linus-ha! It's a good idea.

I added this feature to the `dev` [branch](https://github.com/urpylka/docker-aptly/tree/dev). To use it:

* pull `urpylka/aptly:dev` image
* define docker env param `NGINX_CLIENT_MAX_BODY_SIZE='100M'`

Please check it and let me know how it works.

**Comment by linus-ha** [comment]
Thank you for the fast and extremely helpful response!
Yes, that works quite well. When not setting the variable, the limit defaults to 100M. My issue is solved and this works perfectly. Thank you very much! I think you can merge that or release it with the next version.

**Comment by urpylka** [comment]
Use version v1.5 https://github.com/urpylka/docker-aptly/releases/tag/v1.5
