### ISSUE TITLE
Fix Dead Link Found

### ISSUE THREAD

**Issue by ThinhH151** [urpylka/docker-aptly#14]
I have found Link in [docs/README#line112]( https://github.com/urpylka/docker-aptly/blob/master/docs/README.md?plain=1#L112) cannot access:

`https://morph027.gitlab.io/post/protect-aptly-api-with-basic-authentication/`

I think it could be changed to: `https://morph027.gitlab.io/blog/protect-aptly-api-with-basic-authentication/`

Please check it. Thanks

**Comment by urpylka** [comment]
Hi @ThinhH151 thank you for finding the problem. Please create PR.

**Comment by urpylka** [comment]
Solved
